#!/usr/bin/env python

"""Amulet tests on a basic barbican deployment on cosmic-rocky for keystone v2.
"""

from basic_deployment import BarbicanBasicDeployment

if __name__ == '__main__':
    deployment = BarbicanBasicDeployment(series='cosmic', keystone_version=3)
    deployment.run_tests()
