#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on bionic-train for keystone v3.
"""

from basic_deployment import BarbicanBasicDeployment

if __name__ == '__main__':
    deployment = BarbicanBasicDeployment(series='bionic',
                                         openstack='cloud:bionic-train',
                                         source='cloud:bionic-train')
    deployment.run_tests()
