#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on bionic-stein for keystone v3.
"""

from basic_deployment import BarbicanBasicDeployment

if __name__ == '__main__':
    deployment = BarbicanBasicDeployment(series='bionic',
                                         openstack='cloud:bionic-stein',
                                         source='cloud:bionic-stein')
    deployment.run_tests()
