#!/usr/bin/env python

"""Amulet tests on a basic barbican deployment on xenial-mitaka for keystone v3.
"""

from basic_deployment import BarbicanBasicDeployment

if __name__ == '__main__':
    deployment = BarbicanBasicDeployment(series='xenial', keystone_version=3)
    deployment.run_tests()
