#!/usr/bin/env python

"""Amulet tests on a basic barbican deploy on bionic-rocky for keystone v3.
"""

from basic_deployment import BarbicanBasicDeployment

if __name__ == '__main__':
    deployment = BarbicanBasicDeployment(series='bionic', keystone_version=3,
                                         openstack='cloud:bionic-rocky',
                                         source='cloud:bionic-updates/rocky')
    deployment.run_tests()
