#!/usr/bin/env python

"""Amulet tests on a basic barbican deployment on artful-pike for keystone v2.
"""

from basic_deployment import BarbicanBasicDeployment

if __name__ == '__main__':
    deployment = BarbicanBasicDeployment(series='artful', keystone_version=2)
    deployment.run_tests()
