- project:
    templates:
    - openstack-python3-charm-jobs-2024.1
    - openstack-cover-charm-jobs
    check:
      jobs:
      - charmbuild
    vars:
      charmbuild_charmcraft_channel: 2.x/stable
      charm_build_name: barbican
